### ISSUE TITLE
Bypass error

### ISSUE THREAD

**Issue by Toshiba1127** [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#4]
Doesn't really work for me. This script couldn't bypass this video

https://www.youtube.com/watch?v=yBdBS32Fr68

Errors are printed in the console

```
userscript.html?name=Simple%20YouTube%20Age%20Restriction%20Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:82 Simple-YouTube-Age-Restriction-Bypass-Error: DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://www.youtube.com/get_video_info?video_id=yBdBS32Fr68&html5=1&eurl&ps=desktop-polymer&el=adunit&cbr=Chrome&cplatform=DESKTOP&break_type=1&autoplay=1&content_v&authuser=0'.
    at XMLHttpRequest.send (<anonymous>:53:10)
    at getUnlockedPlayerResponse (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Simple%2520YouTube%2520Age%2520Restriction%2520Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:119:21)
    at unlockPlayerResponse (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Simple%2520YouTube%2520Age%2520Restriction%2520Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:95:37)
    at inspectJsonData (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Simple%2520YouTube%2520Age%2520Restriction%2520Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:78:30)
    at set (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Simple%2520YouTube%2520Age%2520Restriction%2520Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:44:37)
    at https://www.youtube.com/watch?v=yBdBS32Fr68:20:12696
inspectJsonData @ userscript.html?name=Simple%20YouTube%20Age%20Restriction%20Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:82
VM14:53 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
XMLHttpRequest.send @ VM14:53
userscript.html?name=Simple%20YouTube%20Age%20Restriction%20Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:82 Simple-YouTube-Age-Restriction-Bypass-Error: DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://www.youtube.com/get_video_info?video_id=yBdBS32Fr68&html5=1&eurl&ps=desktop-polymer&el=adunit&cbr=Chrome&cplatform=DESKTOP&break_type=1&autoplay=1&content_v&authuser=0'.
    at XMLHttpRequest.send (<anonymous>:53:10)
    at getUnlockedPlayerResponse (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Simple%2520YouTube%2520Age%2520Restriction%2520Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:119:21)
    at unlockPlayerResponse (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Simple%2520YouTube%2520Age%2520Restriction%2520Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:95:37)
    at inspectJsonData (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Simple%2520YouTube%2520Age%2520Restriction%2520Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:78:30)
    at set (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Simple%2520YouTube%2520Age%2520Restriction%2520Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:44:37)
    at https://www.youtube.com/watch?v=yBdBS32Fr68:20:34353
inspectJsonData @ userscript.html?name=Simple%20YouTube%20Age%20Restriction%20Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:82
VM14:53 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
XMLHttpRequest.send @ VM14:53
userscript.html?name=Simple%20YouTube%20Age%20Restriction%20Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:82 Simple-YouTube-Age-Restriction-Bypass-Error: DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://www.youtube.com/get_video_info?video_id=yBdBS32Fr68&html5=1&eurl&ps=desktop-polymer&el=adunit&cbr=Chrome&cplatform=DESKTOP&break_type=1&autoplay=1&content_v&authuser=0'.
    at XMLHttpRequest.send (<anonymous>:53:10)
    at getUnlockedPlayerResponse (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Simple%2520YouTube%2520Age%2520Restriction%2520Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:119:21)
    at unlockPlayerResponse (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Simple%2520YouTube%2520Age%2520Restriction%2520Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:95:37)
    at inspectJsonData (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Simple%2520YouTube%2520Age%2520Restriction%2520Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:78:30)
    at JSON.window.JSON.parse (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Simple%2520YouTube%2520Age%2520Restriction%2520Bypass.user.js&id=7031570e-180c-4a85-8bb5-3232504087fc:56:16)
    at oV.bp (https://www.youtube.com/s/player/38c5f870/player_ias.vflset/en_US/base.js:8215:71)
    at XMLHttpRequest.<anonymous> (https://www.youtube.com/s/player/38c5f870/player_ias.vflset/en_US/base.js:8213:25)
```

**Comment by zerodytrash** [comment]
Hi,

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/3ac35bf1bd62765d344e547a93cf377fa7381d37

The video mentioned seems to be a bit different than other age restricted videos. I have added more parameters to the `/get_video_info` endpoint. That should fix the issue.

**Comment by EchoDev** [comment]
@zerodytrash 

Does this video work for you? 

https://www.youtube.com/watch?v=PaQzgF95Gv4

**Comment by zerodytrash** [comment]
jep, thats it, thanks @JustOff 

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/commit/8a29b67130df8cc9f4eca5d613780e861496036a

Both videos work now, even with uBlock!!!

**Comment by EchoDev** [comment]
Yep, can confirm both videos work.

Thanks @JustOff and @zerodytrash

**Comment by Toshiba1127** [comment]
Thanks guys. it works now
